version: '3'

services:
  db_auth:
    container_name: db_auth
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=db_auth
    image: postgres:14.11-alpine

  my_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_app_container
    ports:
     - "8085:8080"
    depends_on:
      - db_auth
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_auth:5432/db_auth
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=root
    image: my_app